### ISSUE TITLE
Meatballs can be a f'ing salad?

### ISSUE THREAD

**Issue by jimlindstrom** [BrentWheeldon/meatballs#3]
http://www.thesmilenyc.com/?tab=smile-to-go-menus#smile-to-go

Appending `|| !!page.find("#smile-to-go-menus #dinner").text.match(/salad.*meatball/mi)` to https://github.com/BrentWheeldon/meatballs/blob/master/app/controllers/home_controller.rb#L5 seems to do the trick.

**Comment by BrentWheeldon** [comment]
@jimlindstrom This is a massive bug. Working on a fix now. In the meantime, I think this gif sums it up:

![img](http://orig10.deviantart.net/290c/f/2014/118/5/9/30e6w_by_moonchild189-d7gehko.gif)

**Comment by BrentWheeldon** [comment]
Investigated in person, seems like a data entry issue on Smile's side. #WONTFIX
